explicitly require 'activesupport' (before as/core_ext) so that tests run fine
... without the require :

```
Using JBundler to load killbill-api (see .jbundler/classpath.rb). This should only happen in development mode!
LoadError: no such file to load -- active_support/autoload
          require at org/jruby/RubyKernel.java:1072
   ActiveMerchant at /home/kares/workspace/oss/killbill/killbill-plugin-framework-ruby/lib/killbill/helpers/active_merchant.rb:9
```