gen: fix require_gen
org.killbill.billing.util.nodes and org.killbill.billing.security.api
weren't passed to the generator, causing the wrong require_gen to be generated.

Without it, a plugin wouldn't start properly with cryptic errors such as:

ArgumentError: wrong number of arguments calling `initialize` (1 for 0)
               new at org/jruby/java/proxies/JavaInterfaceTemplate.java:451
  create_proxy_api at /lib/killbill/killbill_api.rb:51
        initialize at /lib/killbill/killbill_api.rb:19
              each at org/jruby/RubyHash.java:1341
              each at org/jruby/java/proxies/MapJavaProxy.java:414
        initialize at /lib/killbill/killbill_api.rb:18
            create at /lib/killbill/creator.rb:31
        initialize at /lib/killbill/jplugin.rb:41
        initialize at /lib/killbill/gen/plugin-api/notification_plugin_api.rb:38
        initialize at /lib/killbill/gen/plugin-api/payment_plugin_api.rb:39

Signed-off-by: Pierre-Alexandre Meyer <pierre@mouraf.org>